version: '3'
services:
  brat_al_tool:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    # entrypoint:
    #   [
    #     "python",
    #     "start.py",
    #     "--label",
    #     "drug",
    #     "--label_list",
    #     "O",
    #     "B-drug",
    #     "I-drug"
    #   ]
