version: '3'
services:
  brat_al_tool:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./app/doc:/brat/doc
      - ./app/model:/brat/model
      - ./app/evaluation:/brat/evaluation
      - ./app/data:/brat/data
